todo: test spinningcube spinningcube_withlight

LDLIBS=-lGL -lGLEW -lglfw -lm 

spinningcube_withlight: spinningcube_withlight.o textfile.o

clean:
	rm -f *.o *~

cleanall: clean
	rm -f test spinningcube spinningcube_withlight
